runtime: custom
env: flex

# This tells App Engine to use the Dockerfile in the current directory
service: default

# Adjust resources as needed
resources:
  cpu: 1
  memory_gb: 4
  disk_size_gb: 10

# Environment variables
env_variables:
  ENV: 'prod'
  PORT: '8080'
  USE_OLLAMA_DOCKER: 'false'
  USE_CUDA_DOCKER: 'false'
  USE_CUDA_DOCKER_VER: 'cu121'
  USE_EMBEDDING_MODEL_DOCKER: 'sentence-transformers/all-MiniLM-L6-v2'
  USE_RERANKING_MODEL_DOCKER: ''
  OLLAMA_BASE_URL: '/ollama'
  OPENAI_API_BASE_URL: ''
  OPENAI_API_KEY: ''
  WEBUI_SECRET_KEY: ''
  SCARF_NO_ANALYTICS: 'true'
  DO_NOT_TRACK: 'true'
  ANONYMIZED_TELEMETRY: 'false'
  WHISPER_MODEL: 'base'
  WHISPER_MODEL_DIR: '/app/backend/data/cache/whisper/models'
  RAG_EMBEDDING_MODEL: '${USE_EMBEDDING_MODEL_DOCKER}'
  RAG_RERANKING_MODEL: '${USE_RERANKING_MODEL_DOCKER}'
  SENTENCE_TRANSFORMERS_HOME: '/app/backend/data/cache/embedding/models'
  HF_HOME: '/app/backend/data/cache/embedding/models'

# Network settings
network:
  forwarded_ports:
    - 8080

# Scaling settings
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.6

# Health check
health_check:
  enable_health_check: True
  check_interval_sec: 5
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2

# Specify the Dockerfile to use
beta_settings:
  cloud_sql_instances: ''

# You might need to adjust this depending on your project structure
entrypoint: bash backend/start.sh